Save commit

diff --git a/ace b/ace
--- a/ace
+++ b/ace
@@ -1,5 +1,15 @@
 #!/bin/bash
 
+[[ $_ != $0 ]] && {
+export PATH="$PATH:$PWD"
+export CFLAGS=""
+export ROOTDIR=$PWD
+echo 'Setup done'
+return 0
+}
+
+cd $ROOTDIR
+
 NC='\033[0m'
 RED='\033[31m'
 GREEN='\033[32m'
@@ -57,7 +67,7 @@ details() {
 			echo 'GTKWave needs a valid trace file'
 			;;
 		create)
-			echo 'usage: ace create <module>]'
+			echo 'usage: ace create <module>'
 			echo
 			echo 'All modules are located in the src folder, all'
 			echo 'testbenches in the test folder. Testbenches should'
@@ -97,17 +107,17 @@ clean() {
 compile() {
 	FILE=$1
 	BUILD=`basename ${1%.v}`
-	iverilog -o build/$BUILD $CFLAGS -Isrc -Itest `utils/list-deps $FILE`
+	iverilog -o build/run.vvp $CFLAGS -Isrc -Itest `utils/list-deps $FILE`
 }
 
 check_files() {
 	[[ $# -gt 0 ]] || return 1
 	for FILE in $@ ; do
-		if compile $FILE 2> build/tmp ; then
+		if compile $FILE 2> build/compile.log ; then
 			echo -e "[${GREEN}Ok${NC}]    $FILE"
 		else
 			echo -e "[${RED}Error${NC}] $FILE"
-			[[ $ARG_QUIET -eq 1 ]] || cat build/tmp
+			[[ $ARG_QUIET -eq 1 ]] || cat build/compile.log
 		fi
 	done
 }
@@ -130,7 +140,7 @@ check() {
 		FILES=(`find . -type f -name "*.v"`)
 		check_files ${FILES[@]}
 	else
-		[[ $# -gt 0 ]] || die "No files specified"
+		[[ $# -gt 0 ]] || die 'No arguments'
 		for ARG in "$@" ; do
 			ARG=${ARG%.v}.v
 			FILES=(`find . -type f -path "./*${ARG}"`)
@@ -143,7 +153,7 @@ list_todos() {
 	awk '/\/{2}\s*TODO\s*(.*)/ {
 		gsub(/[^/]*\/*\s*TODO\s*/, "");
 		print $0; f=1
-	} END { exit f }' $1 > build/tmp
+	} END { exit f }' $1 > build/todo.log
 }
 
 
@@ -154,7 +164,7 @@ todo_files() {
 			echo -e "[${GREEN}Ok${NC}]   $FILE"
 		else
 			echo -e "[${BLUE}Todo${NC}] $FILE"
-			[[ $ARG_QUIET -eq 1 ]] || cat build/tmp
+			[[ $ARG_QUIET -eq 1 ]] || cat build/todo.log
 		fi
 	done
 }
@@ -177,7 +187,7 @@ todo() {
 		FILES=(`find . -type f -name "*.v"`)
 		todo_files ${FILES[@]}
 	else
-		[[ $# -gt 0 ]] || die "No files specified"
+		[[ $# -gt 0 ]] || die "No arguments"
 		for ARG in "$@" ; do
 			ARG=${ARG%.v}.v
 			FILES=(`find . -type f -path "./*${ARG}"`)
@@ -187,11 +197,11 @@ todo() {
 }
 
 runtest() {
-	[[ $# -gt 0 ]] || die "No testbench"
 	[[ -z $ARG_TRACE ]] || CFLAGS="$CFLAGS -DTRACEFILE=\"$ARG_TRACE\""
 	FILE=${1%.v}.v
-	compile $FILE 2> build/tmp || die "Unable to build"
-	build/`basename ${1%.v}`
+	compile $FILE 2> build/compile.log || die "Unable to build"
+	build/run.vvp
+	[[ $ARG_GTK -eq 1 ]] && [[ -z $ARG_TRACE ]] && die 'Option -g ignored'
 	[[ $ARG_GTK -eq 1 ]] || exit 0
 	ps | grep -sq gtkwave && die "GTKWave already running"
 	gtkwave -A -f $ARG_TRACE >/dev/null 2>&1 &
@@ -200,6 +210,7 @@ runtest() {
 testbench() {
 	TEMP=`getopt -o gt: -- "$@"`
 	ARG_GTK=0
+	ARG_TRACE=
 	eval set -- "$TEMP"
 	mkdir -p build
 	while true ; do
@@ -210,6 +221,7 @@ testbench() {
 			*) die "Unrecognized option $1" ;;
 		esac
 	done
+	[[ $# -gt 0 ]] || die "No testbench"
 	runtest "$1"
 }
 
@@ -217,6 +229,8 @@ run() {
 	TEMP=`getopt -o gx:t:m:d: -- "$@"`
 	ARG_GTK=0
 	ARG_MAIN="test/cpu_tb.v"
+	ARG_TRACE=
+	ARG_OUTPUT=
 	eval set -- "$TEMP"
 	mkdir -p build
 	while true ; do
@@ -247,9 +261,12 @@ case $CMD in
 		;;
 	check) check "$@" ;;
 	todo) todo "$@" ;;
-	create) utils/boilerplate "${1%.v}" ;;
+	create)
+		[[ $# -gt 0 ]] || die 'No arguments'
+		utils/boilerplate "${1%.v}" ;;
 	clean) clean ;;
 	test) testbench "$@" ;;
 	run) run "$@" ;;
+	asm) die "Not implemented yet" ;;
 	*) usage ;;
 esac
